### ISSUE TITLE
How to use with tox

### ISSUE THREAD

**Issue by graingert** [paylogic/pip-accel#30]
At the moment we use tox to build our virtualenvs before tests.

It doesn't seem possible to call an externally installed `pip-accel` from within another virtualenv (it installs it to the host virtualenv), nor to install `pip-accel` into the virtualenv before the install process of tox starts

**Comment by bh** [comment]
I got the same issue a half year ago. 
I fixed it with setting the VIRTUAL_ENV env variable in tox.ini:

```
[tox]
skipsdist = True
envlist = py34
toxworkdir = {toxinidir}/.tox

[testenv]
# on jenkins we always recreate the whole
# workspace, so tox will be implicitly recreated
recreate = False
whitelist_externals = make
setenv =
    VIRTUAL_ENV={toxworkdir}/{envname}
    DJANGO_CONFIGURATION=Jenkins

# run the commands in a Makefile target to exit if one command failes
# https://bitbucket.org/hpk42/tox/issue/124/ignore-command-exit-codes
commands = make ci_run_tests
```

**Comment by hashar** [comment]
tox 1.8+ should now export VIRTUAL_ENV.  At least according to https://bitbucket.org/hpk42/tox/issues/152
