### ISSUE TITLE
Doesn't run on windows

### ISSUE THREAD

**Issue by ratiotile** [paylogic/pip-accel#53]
Fresh install of Python 3.4.3, ran `python -m pip install pip-accel`, success.

`pip-accel -h`, then gives `ImportError: No module named 'pwd'`

**Comment by matysek** [comment]
I confirm it. It does not run on Windows.

**Comment by matysek** [comment]
@ratiotile Could you please try if the version from the pull request works for you on Windows?

**Comment by ratiotile** [comment]
@matysek How do I clone the pull request?

**Comment by ratiotile** [comment]
@matysek nevermind, I managed to figure it out. Works for me on windows 8.1, python 3.4.3. Although strangely there was no output the first time I ran `pip-accel -h`.

Seems to buffer the output, and only print out after the next command is run.
input: `pip-accel foo`
output: 
input: `pip-accel`
output: `Error: unknown command "foo"`
`Usage: pip-accel ...`

**Comment by xolox** [comment]
Pull requests #60 and #61 have been merged and a new release has been published to PyPI, so pip-accel should now (starting from version 0.33) fully support Windows! AppVeyor CI is used to automatically test all changes on Windows so I don't break compatibility later. If you encounter any issues in the new Windows support feel free to open a new issue. Thanks for the feedback!
