### ISSUE TITLE
Doesn't work with pip 7+

### ISSUE THREAD

**Issue by jimbobhickville** [paylogic/pip-accel#57]
pip is pinned to between versions 6.0.8 and 6.2.  pip is on version 7.1 now.  Can we get pip-accel updated to work with newer pip?  We need some of the newer features of pip and would like to use pip-accel.

**Comment by xolox** [comment]
Hi Greg and thanks for the feedback! Sorry it took me a while to tackle this issue. Today I upgraded the pip dependency to 7.1 (the commits are referenced in this issue) and I released pip-accel 0.32.1 to PyPI. Please try out the new version and let me know if you find any issues.

**Comment by xolox** [comment]
I'm going to close this issue now because pip 7 support was released more than a month ago and I've been using it daily since then, also no relevant new issues have been reported. Thanks again for the feedback!
