### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by azmeuk** [paylogic/pip-accel#78]
Hi. There has been two years since a single commit or bug report, so I wast just wondering. Is this project still alive?

**Comment by artynet** [comment]
I started working on a compatibility patch here :

https://github.com/paylogic/py2deb/issues/27

would you mind taking a look at it @azmeuk ?

**Comment by moi90** [comment]
> Is this project still alive?

Probably not...

It would be great if the maintainers could make a last update stating that `pip-accel` is obsolete.
